import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const appSource = readFileSync(resolve("src/App.tsx"), "utf8");
const readmeSource = readFileSync(resolve("../README.md"), "utf8");
const viteConfig = readFileSync(resolve("vite.config.ts"), "utf8");
const packageJson = JSON.parse(readFileSync(resolve("package.json"), "utf8"));
const sampleReport = JSON.parse(readFileSync(resolve("public/sample-report.json"), "utf8"));

assert.equal(sampleReport.schemaVersion, "1.0");
assert.ok(Array.isArray(sampleReport.findings));
assert.equal(sampleReport.baseline.new, 2);
assert.ok(sampleReport.findings.some((finding) => finding.id === "risk.github.pull-request-target"));
assert.match(appSource, /Know what changed before install scripts run/);
assert.match(appSource, /depsaber wizard/);
assert.match(appSource, /Launch sequence/);
assert.match(appSource, /Report console/);
assert.match(appSource, /Sample report loaded/);
assert.match(appSource, /This bundled report is an example/);
assert.match(appSource, /Load local report/);
assert.match(appSource, /Report source/);
assert.match(appSource, /Use your own report/);
assert.match(appSource, /Generate \.depsaber\/report\.json/);
assert.match(appSource, /Install the CLI/);
assert.match(appSource, /https:\/\/reymundotenorio\.github\.io\/depsaber\//);
assert.match(appSource, /resolved/);
assert.match(appSource, /severity/i);
assert.match(appSource, /\.depsaber\/report\.json/);
assert.match(appSource, /import\.meta\.env\.BASE_URL/);
assert.match(readmeSource, /actions\/workflows\/pages\.yml\/badge\.svg\?branch=main/);
assert.match(readmeSource, /actions\/workflows\/release\.yml\/badge\.svg/);
assert.match(readmeSource, /github\/v\/release\/reymundotenorio\/depsaber/);
assert.match(readmeSource, /github\/go-mod\/go-version\/reymundotenorio\/depsaber/);
assert.match(readmeSource, /report%20viewer-online-71f9e8/);
assert.equal(packageJson.scripts["preview:pages"], "node scripts/preview-pages.mjs");
assert.match(viteConfig, /DEPLOY_TARGET/);
assert.match(viteConfig, /\/depsaber\//);
